### ISSUE TITLE
建议更换博文《LaTeX3 教程（一）》中 \CTEX@replacecommand 的例子

### ISSUE THREAD

**Issue by muzimuzhi** [stone-zeng/stone-zeng.github.io#1]
博文《[LaTeX3 教程（一）](https://stone-zeng.github.io/2019-02-24-l3tutorial-background/)》中用`\CTEX@replacecommand` 的定义给「丧心病狂的宏展开」作例子。建议更换这个例子

这个例子引用自 2014 年的一个[知乎问题](https://www.zhihu.com/question/26916597)（博文注释提供了链接），从那时到现在，ctex 宏集已经有了不小的更新（例如，用 latex3 重写、选项设置命令和选项名的改变）。当前，在 ctex 宏集的源码中已不存在宏 `\CTEX@replacecommand`，源码中也不存在类似的可以给「丧心病狂的宏展开」作例子的用法。原知乎问题下的回答，是学习 `\expandafter` 不错但材料，但是在新博文中（继续）使用这个例子，可能给好奇心重的读者带来困惑。

宏定义中连续使用 `\expandafter` 的例子并不难找，建议更换一个例子。

**Comment by stone-zeng** [comment]
这个例子我还是保留下来了，毕竟分析很透彻。之前版本的 `ctex` 仍然保留在 [`ctex-1.02d`](https://github.com/CTeX-org/ctex-kit/tree/ctex-1.02d) 分支里面，所以这段代码还是可以找的到的：<https://github.com/CTeX-org/ctex-kit/blob/ctex-1.02d/def/ctex-common.def#L44-L50>。
