### ISSUE TITLE
博客 markdown 代码块在显示 JSON 格式代码时背景色问题

### ISSUE THREAD

**Issue by SwitWu** [stone-zeng/stone-zeng.github.io#36]
曾老师，不好意思打扰到您，我用了您的这个博客框架，然后有一个小问题：

在 markdown 中使用代码块，语言选定为 json，内容如下：

```json
// 保存时就启动 Build 编译，Build 默认调用 recipe 中的第一条命令，这里默认注释掉，如果需要可以取消注释
"latex-workshop.latex.autoBuild.run": "never",
```

博客渲染的结果：

![json](https://user-images.githubusercontent.com/39337667/236433214-6a2ba003-e795-4b0a-90b5-ccbaf7d553d1.png)

可以看到，中英文之间红色背景块发生断裂，而且代码最后的逗号也被赋予红色背景块，请问这个问题怎么改善一下？谢谢您！

**Comment by stone-zeng** [comment]
GitHub Pages 默认使用的 highlighter 是 [Rouge](https://github.com/rouge-ruby/rouge)，也许可以试一下把语言换成 `json-doc`。

**Comment by SwitWu** [comment]
解决了，逗号那里的问题是因为我没有在最外层添加花括号。感谢曾老师！
